dist: xenial
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django18

install:
  - pip install tox

script:
  - tox -e $TOXENV
